defaultEntryPoints = ["http", "https"]

[web]
# Port for the status page
address = ":8080"

# Entrypoints, http and https
[entryPoints]
# http should be redirected to https
[entryPoints.http]
address = ":80"
[entryPoints.http.redirect]
entryPoint = "https"
# https is the default
[entryPoints.https]
address = ":443"
[entryPoints.https.tls]

# Enable ACME (Let's Encrypt): automatic SSL
[acme]
# Email address used for registration
OnHostRule = true
email = "mr.rahultanwar@gmail.com"
entryPoint = "https"
onDemand = false
storageFile = "/etc/traefik/acme/acme.json"
# Use a HTTP-01 acme challenge rather than TLS-SNI-01 challenge
[acme.httpChallenge]
entryPoint = "http"

# Enable Docker configuration backend
[docker]
domain = "rahultanwar.me"
endpoint = "unix:///var/run/docker.sock"
exposedbydefault = false
watch = true
